import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  guide: [
    'intro',
    {
      type: 'category',
      label: 'Install',
      collapsed: false,
      items: ['install-docker', 'run-reelcraft'],
    },
    {
      type: 'category',
      label: 'Set up',
      collapsed: false,
      items: ['provider-keys', 'browseros-neo', 'codex'],
    },
    {
      type: 'category',
      label: 'Concepts',
      collapsed: false,
      items: ['concepts/how-it-works', 'concepts/glossary'],
    },
    {
      type: 'category',
      label: 'Channels',
      collapsed: true,
      items: ['channels/channels', 'channels/defaults', 'channels/characters', 'channels/assets'],
    },
    {
      type: 'category',
      label: 'Building blueprints',
      collapsed: true,
      items: [
        'blueprints/blueprints',
        'blueprints/assistant',
        'blueprints/versions',
        'blueprints/sharing',
        'blueprints/settings',
        'blueprints/stages',
        'blueprints/connecting-stages',
        'blueprints/prompts',
        'blueprints/outputs',
        'blueprints/models',
        'blueprints/iterate-conditions-approval',
        'blueprints/checks',
        'blueprints/quality-control',
      ],
    },
    {
      type: 'category',
      label: 'Stage types',
      collapsed: true,
      items: [
        'stage-types/index',
        'stage-types/generate-text',
        'stage-types/generate-image',
        'stage-types/generate-video',
        'stage-types/generate-speech',
        'stage-types/analyze-media',
        'stage-types/concatenate-video',
        'stage-types/render-timeline',
        'stage-types/export-subtitles',
        'stage-types/human-input',
        'stage-types/human-timeline-edit',
        'stage-types/automate-browser',
        'stage-types/generate-video-with-flow',
      ],
    },
    {
      type: 'category',
      label: 'Runs',
      collapsed: true,
      items: [
        'runs/starting-a-run',
        'runs/dry-runs',
        'runs/canvas-runs',
        'runs/runs-list',
        'runs/run-page',
        'runs/when-a-run-needs-you',
        'runs/retries',
        'runs/budget-and-costs',
        'runs/pause-resume-cancel',
        'runs/outputs-and-downloads',
        'runs/when-a-stage-fails',
      ],
    },
    {
      type: 'category',
      label: 'Making the video',
      collapsed: true,
      items: [
        'video/assembly',
        'video/timelines',
        'video/timeline-editor',
        'video/timeline-checks',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: true,
      items: [
        'reference/run-statuses',
        'reference/built-in-checks',
        'reference/validation-messages',
        'reference/costs',
      ],
    },
    {
      type: 'category',
      label: 'Look after it',
      collapsed: false,
      items: ['updating', 'backup', 'troubleshooting'],
    },
  ],
};

export default sidebars;
